analytics: {}
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.920373
  lightness: 0.418072
  rhythmicContrast: 0.75
  saturation: 0.318457
cta: {}
layout_spectrum: 0
name: WhyStandWhenYouCanSit
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.33424
