analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#888888'
    - '#000000'
    - '#000000'
  brandStrength: 0.920373
  lightness: 0.418072
  rhythmicContrast: 0.632303
  saturation: 0.318457
cta: {}
layout_spectrum: 0.026315
name: WhyStandWhenYouCanSit
opengraph: {}
purpose: {}
typography_spectrum: 0.38898
