name: WhyStandWhenYouCanSit
favicon: null
layout_spectrum: 0.026315
typography_spectrum: 0.38898
title: HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#888888'
    - '#000000'
    - '#000000'
  brandStrength: 0.920373
  lightness: 0.418072
  saturation: 0.318457
  rhythmicContrast: 0.632303
purpose:
  - name: null
    item: null
    url: null
